[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin14-clang"
ar = "x86_64-apple-darwin14-ar"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-unknown-linux-musl-gcc"
ar = "aarch64-unknown-linux-musl-ar"
