[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin14-clang"
ar = "x86_64-apple-darwin14-ar"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-unknown-linux-musl-gcc"
ar = "x86_64-unknown-linux-musl-ar"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-unknown-linux-musl-gcc"
ar = "aarch64-unknown-linux-musl-ar"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"
