# Compile release bulids for the following platforms:
# - Windows (x86_64-pc-windows-gnu)
# - Linux (x86_64-unknown-linux-musl, aarch64-unknown-linux-musl)
#- macOS (x86_64-apple-darwin)

name: Compile release builds

on:
  workflow_dispatch:

jobs:
  build:
    name: Compile all binaries
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - name: Install cross
        run: cargo binstall cross -y
      - name: Compile aarch64-unknown-linux-musl
        run: cross build --release --target aarch64-unknown-linux-musl
      - name: Compile x86_64-unknown-linux-musl
        run: cross build --release --target x86_64-unknown-linux-musl
      - name: Compile x86_64-pc-windows-gnu
        run: cross build --release --target x86_64-pc-windows-gnu
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: "Upload binary: aarch64-unknown-linux-musl"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/aarch64-unknown-linux-musl/release/dns-updater
          asset_name: dns-updater_aarch64-unknown-linux-musl
          asset_content_type: application/octet-stream
      - name: "Upload binary: x86_64-unknown-linux-musl"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/x86_64-unknown-linux-musl/release/dns-updater
          asset_name: dns-updater_x86_64-unknown-linux-musl
          asset_content_type: application/octet-stream
      - name: "Upload binary: x86_64-pc-windows-gnu"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/x86_64-pc-windows-gnu/release/dns-updater.exe
          asset_name: dns-updater_x86_64-pc-windows-gnu.exe
          asset_content_type: application/octet-stream
