# Compile release bulids for the following platforms:
# - Windows (x86_64-pc-windows-gnu)
# - Linux (x86_64-unknown-linux-musl, aarch64-unknown-linux-musl)
#- macOS (x86_64-apple-darwin)

name: Compile release builds

on:
  workflow_dispatch:

jobs:
  build:
    name: Compile all binaries
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Compile aarch64-unknown-linux-musl
        run: cross build --release --target aarch64-unknown-linux-musl
      - name: Compile x86_64-unknown-linux-musl
        run: cross build --release --target x86_64-unknown-linux-musl
      - name: Compile x86_64-pc-windows-gnu
        run: cross build --release --target x86_64-pc-windows-gnu
      - name: Create builds artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            target/aarch64-unknown-linux-musl/release/dns-updater
            target/x86_64-unknown-linux-musl/release/dns-updater
            target/x86_64-pc-windows-gnu/release/dns-updater.exe
